### ISSUE TITLE
Bot dosent save text correctly

### ISSUE THREAD

**Issue by DelphiDv** [OtakuMegane/DerpyBot#10]
I noticed it never saved people being pinged as <@id>, but just as if it copised and pasted their username, is this an intentional bit in the code to prevent the bot from pinging people or the byproduct of something else.

**Comment by OtakuMegane** [comment]
I actually forget why it doesn't, but I never tried changing it because it would annoy a bunch of people if it actually pinged them.

I can look at if it's possible to do and if so add an opt-in setting to allow pings.

**Comment by DelphiDv** [comment]
Okay thanks

**Comment by DelphiDv** [comment]
Also why does it not saves any capital letters.

**Comment by OtakuMegane** [comment]
It's fairly difficult to get capitalization right when generating replies and handling stuff in lowercase was more practical. It does preserve URLs since those aren't subject to grammar.

**Comment by DelphiDv** [comment]
I see, but in what part of code the code does it cancels capitalisation, i wanna see how it would look like with capitalisation enabled.

**Comment by OtakuMegane** [comment]
The new release now has settings to enable both these things.

Preserving capitalization turned out to be fairly simple but it may somewhat reduce the chances of getting a sentence for keywords. This is activated in the markov config by enabling `preserve_case`.

The other part with pinging was trickier but doable. Ids can now be stored by enabling `raw_to_markov`. The replies generated can also do pings if ids or other mentions are in the text; this one is activated by disabling `clean_output`.
